# Pulse-control v3.13 CDC constraints
#
# fclk[3] / clk_fpga_3 is generated by the Zynq PS and is used for the
# 200 MHz GPIO sequencer plus the external DIO0_P trigger synchronizer/delay.
# pll_adc_clk is derived from the external ADC clock and drives the 125 MHz
# acquisition/group/PID/DAC2 logic.  They are asynchronous clock domains.
#
# Only toggle events and slow, held-stable configuration/readback cross between
# 200 MHz and 125 MHz in the custom pulse-control logic.  The old internal
# GPIO-period -> ADC-domain group-boundary CDC is no longer used; group source 0
# is the delayed external DIO0_P trigger.
set_clock_groups -asynchronous \
    -group [get_clocks clk_fpga_3] \
    -group [get_clocks pll_adc_clk]

# DIO0_P is an asynchronous external trigger, not a synchronous input relative
# to either FPGA clock.  The RTL immediately feeds it into a two-flop ASYNC_REG
# synchronizer in external_group_trigger_v3, so there is intentionally no input
# timing requirement from the package pin to that first synchronizer stage.
set_false_path -from [get_ports {exp_p_io[0]}]

# Do NOT globally declare clk_fpga_0 asynchronous to pll_adc_clk here.
# The stock Red Pitaya sys_bus_cdc constraints already use point-to-point
# set_max_delay -datapath_only constraints for that crossing.  A broad
# set_clock_groups would override those constraints (Vivado TIMING-24).
